#!/bin/bash

$PROOFWALLET view-addresses -m 2 -n 3 --trust-xpubs --regtest << INPUT 2>&1
y
y
y
y
y
y
[2eb4fc90/48'/1'/0'/2']tpubDFFFhev78PB1E9LUcWoeBrwJUQrhH23f2ShmW4DueA6WDkd27qgyJeWNL62FcNQHbh6wAJhGhYm2g3xQidQ6G2SpNBh8qon3HLhc6vYzyJy
[41f408e8/1']tpubD8kF7X4sjY6y5zRgmYhjd4878gYVtuesSxo8zhYkNdb5KRZK7tU42yS2RTBA6Mn86VRfRXk6RqJ6FQ35tDaLxyhEGG2SSKAf1ifcYG9fNjX
[2eb4fc90]tpubD6NzVbkrYhZ4WX5Vw6NH1JxG2JmogqviDePh8V9Fikp4gA7FzM4sQGiZJvH1TUcE9F3wpGHL8aGp8nLZvjRV6rfFYEQ1Crs6NSoPHSebtnd
INPUT

retVal=$?
if [ $retVal -eq 0 ]; then
    echo "Error: expected proofwallet.py to fail"
    exit 1
fi