#!/bin/bash

$PROOFWALLET view-addresses -m 3 -n 5 --trust-xpubs --regtest << INPUT 2>&1
y
y
y
y
y
y
[2eb4fc90/48'/1'/0'/2']tpubDFFFhev78PB1E9LUcWoeBrwJUQrhH23f2ShmW4DueA6WDkd27qgyJeWNL62FcNQHbh6wAJhGhYm2g3xQidQ6G2SpNBh8qon3HLhc6vYzyJy
[41f408e8/1h]tpubD8kF7X4sjY6y5zRgmYhjd4878gYVtuesSxo8zhYkNdb5KRZK7tU42yS2RTBA6Mn86VRfRXk6RqJ6FQ35tDaLxyhEGG2SSKAf1ifcYG9fNjX
[3b6b014e]tpubD6NzVbkrYhZ4Wnsni4GBz5MepuDt6zidxNKZUGKQGgokfadLG2Jf33PXRGSfTCC3xjvv2YhCpFGTrShdUq8mCqZPUjpAu9bnPuAf4vt9Apw
[cdefec0e/42/0/1]tpubDCNavbMWfrRD35PnbiiyFACj4P1F7Fn3BmW8xbkXojbqsPMf1GfwUUR3xrDoYvD14YMN9KNT421or8vyufxjoudGZSzkcQg47n9ApVtjBMR
QUIT
INPUT

retVal=$?
if [ $retVal -eq 0 ]; then
    echo "Error: expected proofwallet.py to fail"
    exit 1
fi