#!/bin/bash

../../glacierscript.py sign-psbt -m 2 -n 2 --regtest << INPUT 2>&1
y
y
y
y
y
y
mouse scout chest give trim veteran keen arrive test advice warrior reduce silent useful oak embrace drift curve large poet embody theme focus wolf
tpubD6NzVbkrYhZ4YTjZqdGdMpqtd7BFKkERJcK3hjQx4gtHC3xowC5EKAsHY5tgx1coSC6sbw6X7Ngc1AFrVEzgwFFAF8pbsU5n28yYiZrxTAg
tpubD6NzVbkrYhZ4XcWFWZiEr9DBG7eFbG5H6Lz4TwmMw9FwhaRT7Yj5LyPFFBp7jok8uaPKWYsQtHEK2e1N231CmVt2QfMsjCn46by1NbrFEq9
cHNidP8BAIACAAAAAURrW7a/0IjQJW4qN6xld6NLFTSoGe+WA2VzxApER5svAAAAAAD9////AnzPAwAAAAAAIgAg0oDDltDjDejjGuz/2oGhg0ErfFOuzUJ7fnjQKNgLVGqwcQsAAAAAABl2qRQ0Sg9IyhUOwrkDgXZgubaLE6ZwJoisWXcZAAABAStAQg8AAAAAACIAIObsDL3M58bQU3k5T9aWSPQGPn+pZ4Xm41qatgr3rL1IIgYCAi9g1wJg9FyhlZTAdxINPYA106IBvhSdmmvq3d4D954MNOk82gAAAAAAAAAAIgYD9FUZFcYYgC+97g0KJPZH+9zd+5di4ZMKbICeyY3KNIAMC4ipNwAAAAAAAAAAAAEBR1IhAkimLcHXpa+d9rECiTsGPfLcUeA2R3JiYPx9lb3L968ZIQKmOCJvxUjnwDbkSGcauYc8UOVlBxMxpgH+yIaQKdCa1FKuIgICSKYtwdelr532sQKJOwY98txR4DZHcmJg/H2Vvcv3rxkMC4ipNwEAAAAAAAAAIgICpjgib8VI58A25EhnGrmHPFDlZQcTMaYB/siGkCnQmtQMNOk82gEAAAAAAAAAAAA=
INPUT

retVal=$?
if [ $retVal -eq 0 ]; then
    echo "Error: expected glacierscript.py to fail"
    exit 1
fi
