#!/bin/bash

../../glacierscript.py sign-psbt -m 2 -n 2 --regtest << INPUT 2>&1
y
y
y
y
y
y
mouse scout chest give trim veteran keen arrive test advice warrior reduce silent useful oak embrace drift curve large poet embody theme focus wolf
tpubDDHMqKTaW9a5kRiZb7Cqak3691sdhkiJpLpwaP7m6F32E6c32nitG9Kun5qEKaBnBn1YshNRai6657YoMheZQhLycMPvKzi7ZVHARDkiA7W
tpubD6NzVbkrYhZ4XcWFWZiEr9DBG7eFbG5H6Lz4TwmMw9FwhaRT7Yj5LyPFFBp7jok8uaPKWYsQtHEK2e1N231CmVt2QfMsjCn46by1NbrFEq9
INPUT

retVal=$?
if [ $retVal -eq 0 ]; then
    echo "Error: expected glacierscript.py to fail"
    exit 1
fi
