#!/bin/bash

$PROOFWALLET sign-psbt -m 2 -n 2 --regtest << INPUT 2>&1
y
y
y
y
y
y
viable finger bless corn tomorrow emotion kangaroo there youth impose innocent december swamp reduce famous enter worth search home journey volcano clerk consider noise
[3c906b8e]tpubD6NzVbkrYhZ4WXEkt6oeKnS3dzphc3GMcUtLX2SJungsdQn7VU3Q1d3UsEhHsExS4ho7Bqxcj7SnXzNzUgztedC8EgWcGi5CHPQdtkx2QKf
[b48ba58d]tpubD6NzVbkrYhZ4XATUSvdtr6dWxAQVih5fthjWVF59eYwqf1VmeLwJQHByHhjPhp26jGb6EVxaFqDmNgxuerVBEmwAiTYFgmMjK4ff1PV3y8V
INPUT

retVal=$?
if [ $retVal -eq 0 ]; then
    echo "Error: expected proofwallet.py to fail"
    exit 1
fi
